## Problem_(1)
Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [17]:
# here we importing the numpy library for dealing with our data
import numpy as np

# here we are defining a function to change the inputvector into powers of that inputvector according to question
# ipvector = inputvector
# col_no = no. of columns 

# reshape(ipvector.size,col_no) = reshape(5,5)    
# ipvector.size =  5
# col_no = 5
def gen_power_matrix(ipvector,col_no,increasing="False"):
    if not increasing:                                                                                               # not increasing means decreasing order = x**(N-i-1)
        op_mat = np.array([x**(col_no-1-i) for x in ipvector for i in range(col_no)]).reshape(ipvector.size,col_no)
    elif increasing:                                                                                                 # increasing order = x**(i)
        op_mat = np.array([x**(i) for x in ipvector for i in range(col_no)]).reshape(ipvector.size,col_no)
    return op_mat                                                                                                    # here we are returning our output matrix
 
    

# here we are initializing our input vector as well as column number 
inputvector = np.array([1,2,3,4,5])
op_mat_col_no = 5
op_mat_dec_ord = gen_power_matrix(inputvector,op_mat_col_no,False)
op_mat_inc_ord = gen_power_matrix(inputvector,op_mat_col_no,True)


print("=========================OUTPUT=========================\n")
print("The input array is:",inputvector,"\n")
print("========================================================\n")
print("Number of columns in output matrix should be:",op_mat_col_no,"\n")
print("========================================================\n")
print("Output matrix of the input array in decreasing order of powers:\n\n",op_mat_dec_ord,"\n")
print("========================================================\n")
print("Output matrix of the input array in increasing order of powers:\n\n",op_mat_inc_ord,"\n")

=========================OUTPUT=========================

The input array is: [1 2 3 4 5] 


Number of columns in output matrix should be: 5 


Output matrix of the input array in decreasing order of powers:

 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]] 


Output matrix of the input array in increasing order of powers:

 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]] 



## problem(2)

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [46]:
# here we importing the numpy library for dealing with our data
import numpy as np

# here we are defining a function to find moving average in an array over a window according to question
def moving_average(a, k=3) :
    op = np.cumsum(a, dtype=float)
    op[k:] = op[k:] - op[:-k]
    return op[k - 1:] / k

# here we are initializing our array
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

print("=========================OUTPUT=========================\n")
print(moving_average(a, k=3))


=========================OUTPUT=========================

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]


In [43]:
# ==== how is it working ====
# all operations that is happening in oue second problem
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k=3
op = np.cumsum(a,dtype=float)
print(op)
print(op[k:])
print(op[:-k])
print(op[k-1:])
print((op[k:] - op[:-k])/k)
op[k:] = op[k:] - op[:-k]
print(op[k-1:]/k)

[  3.   8.  15.  17.  25.  35.  46. 111. 183. 264. 363. 463. 613.]
[ 17.  25.  35.  46. 111. 183. 264. 363. 463. 613.]
[  3.   8.  15.  17.  25.  35.  46. 111. 183. 264.]
[ 15.  17.  25.  35.  46. 111. 183. 264. 363. 463. 613.]
[  4.66666667   5.66666667   6.66666667   9.66666667  28.66666667
  49.33333333  72.66666667  84.          93.33333333 116.33333333]
[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
